services:
  nginx:
    container_name: core-nginx
    working_dir: /var/www/app
    image: nginx:alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./var/log/nginx-log:/var/log/nginx
      - ./:/var/www/app
    ports:
      - "8092:80"
    networks:
      - core-network
    depends_on:
      - php

  php:
    container_name: core-php
    working_dir: /var/www/app
    build: ./docker/php
    volumes:
      - ./:/var/www/app
      - ./docker/php/conf/x-php.ini:/usr/local/etc/php/conf.d/custom-docker-php.ini
    networks:
      - core-network
    environment:
      XDEBUG_CONFIG: "client_host=172.17.0.1"
      PHP_IDE_CONFIG: "serverName=xdebug-core"
    depends_on:
      - postgres

  postgres:
    container_name: core-pgsql
    image: postgres:16-alpine
    env_file: .env
    ports:
      - 54329:5432
    networks:
      - core-network
    environment:
      POSTGRES_ROOT_PASSWORD: postgres
      POSTGRES_DATABASE: core
      POSTGRES_USER: core
      POSTGRES_PASSWORD: secret

    volumes:
      - ./var/pg-data:/var/lib/postgresql/data
  redis:
    container_name: core-redis
    image: redis:alpine
    restart: always
    networks:
      - core-network
    ports:
      - "6380:6379"
    volumes:
      - ./var/redis-data:/data
    command: [ "redis-server", "--appendonly", "yes" ]

networks:
  core-network:
    driver: bridge